<?php
/**
 * Portfolio single content.
 *
 * @package bewblur
 */

$post_id      = get_the_ID();
$youtube_url  = function_exists( 'get_field' ) ? get_field( 'youtube_link', $post_id ) : '';
$youtube_id   = function_exists( 'bewblur_get_youtube_id' ) ? bewblur_get_youtube_id( $youtube_url ) : '';
$video_teaser = function_exists( 'get_field' ) ? get_field( 'video_teaser', $post_id ) : '';
$thumbnail_id = get_post_thumbnail_id( $post_id );
$terms        = get_the_terms( $post_id, 'portfolio-type' );
$has_overview = '' !== trim( wp_strip_all_tags( (string) get_post_field( 'post_content', $post_id ) ) );

if ( is_array( $video_teaser ) ) {
	$video_teaser = isset( $video_teaser['url'] ) ? $video_teaser['url'] : '';
} elseif ( is_numeric( $video_teaser ) ) {
	$video_teaser = wp_get_attachment_url( (int) $video_teaser );
}
?>

<article id="post-<?php the_ID(); ?>" <?php post_class( 'content-work' ); ?>>
	<?php if ( $youtube_id || $video_teaser || $thumbnail_id ) : ?>
		<section class="work-single-banner">
			<div class="s-container -wide">
				<div class="work-single-banner__media">
					<?php if ( $youtube_id ) : ?>
						<div class="work-single-banner__embed">
							<iframe
								src="<?php echo esc_url( 'https://www.youtube.com/embed/' . rawurlencode( $youtube_id ) . '?rel=0&modestbranding=1' ); ?>"
								title="<?php echo esc_attr( get_the_title( $post_id ) ); ?>"
								loading="lazy"
								allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
								allowfullscreen
							></iframe>
						</div>
					<?php elseif ( $video_teaser ) : ?>
						<video
							class="work-single-banner__video"
							src="<?php echo esc_url( $video_teaser ); ?>"
							<?php if ( $thumbnail_id ) : ?>poster="<?php echo esc_url( wp_get_attachment_image_url( $thumbnail_id, 'full' ) ); ?>"<?php endif; ?>
							controls
							playsinline
							preload="metadata"
						></video>
					<?php else : ?>
						<?php
						echo wp_get_attachment_image(
								$thumbnail_id,
								'full',
								false,
								array(
									'class'    => 'work-single-banner__thumb',
									'loading'  => 'eager',
									'decoding' => 'async',
								)
							); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress.
						?>
					<?php endif; ?>
				</div>
			</div>
		</section>
	<?php endif; ?>

	<div class="s-container -wide">
		<header class="work-single-intro<?php echo $has_overview ? ' work-single-intro--has-overview' : ' work-single-intro--no-overview'; ?>">
			<div class="work-single-intro__meta">
				<p class="work-single-intro__eyebrow">
					<span class="work-single-intro__dot" aria-hidden="true"></span>
					<?php esc_html_e( 'Selected project', 'bewblur' ); ?>
				</p>
				<p class="work-single-intro__type"><?php esc_html_e( 'Creative production', 'bewblur' ); ?></p>
			</div>

			<div class="work-single-intro__grid">
				<div class="work-single-intro__project">
					<p class="work-single-intro__label"><?php esc_html_e( 'Project', 'bewblur' ); ?></p>
					<?php the_title( '<h1 class="work-single-intro__title">', '</h1>' ); ?>

					<?php if ( ! empty( $terms ) && ! is_wp_error( $terms ) ) : ?>
						<div class="work-single-intro__terms" aria-label="<?php esc_attr_e( 'Portfolio types', 'bewblur' ); ?>">
							<?php foreach ( $terms as $term ) : ?>
								<span class="work-single-intro__term"><?php echo esc_html( $term->name ); ?></span>
							<?php endforeach; ?>
						</div>
					<?php endif; ?>
				</div>

				<?php if ( $has_overview ) : ?>
					<div class="work-single-intro__overview">
						<div class="work-single-intro__overview-head">
							<h2><?php esc_html_e( 'Overview', 'bewblur' ); ?></h2>
							<span aria-hidden="true">01</span>
						</div>
						<div class="work-single-intro__copy entry-content">
							<?php the_content(); ?>
							<?php
							wp_link_pages(
								array(
									'before' => '<div class="page-links">' . esc_html__( 'Pages:', 'bewblur' ),
									'after'  => '</div>',
								)
							);
							?>
						</div>
					</div>
				<?php endif; ?>
			</div>
		</header>
	</div>



    <footer class="entry-footer">
        <?php seed_entry_footer(); ?>
    </footer>
</article>
